spring.application.name=tournamentTable
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/<Ваша БД>
spring.datasource.username=<Логин БД>
spring.datasource.password=<Пароль БД>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.drop-first=false

SECURITY_ADMIN_LOGIN=<Логин Администратора>
SECURITY_ADMIN_PASSWORD=<Пароль Администратора>
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/public/docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.tags.application=${spring.application.name}
management.server.port=8081
management.endpoints.web.base-path=/actuator
